// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duaknujureumxddodkga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1YWtudWp1cmV1bXhkZG9ka2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTk5NjMsImV4cCI6MjA3MTY5NTk2M30.-5Lh1AQrDvNs0tXNcF9TtKHwvc6cojXMxojs2nsfI3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});